### ISSUE TITLE
Consider specifying a license

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/tomlib#16]
Currently tomlib does not specify a license. This unfortunately makes it difficult for some upstream distributors to package tomlib, and they might end up removing it from their GAP installations, which is sad.

Lots of packages used to not specify GAP, esp. when they were still developed as part of the GAP CVS repository, and hence were implicitly assumed to be under the "GPL 2 or later". Perhaps you'd be fine with just keeping that license, which still matches what GAP still uses? If so, I can also prepare a pull request for you adding just that.

**Comment by gpfeiffer** [comment]
Yes please do.

**Comment by fingolfin** [comment]
Will do. Ah, and I just noticed that you say this in the manual already (which I overlooked):
"We adopt the copyright regulations of GAP as detailed in the copyright notice in the GAP manual
