### ISSUE TITLE
list of authors in PackageInfo.g

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/tomlib#18]
When updating some references to GAP packages,
I noticed that Thomas Merkwitz is no longer listed as an author of the TomLib package.
Why has his name been removed?

**Comment by olexandr-konovalov** [comment]
I don't know anything about the authorship of TomLib, but I can clarify that this happened in 2011.

As far as I can see, in this repository the history starts from version 1.2.2 (2011-09-30) which was the fist picked up for the redistribution with GAP, and it already has only two authors on it.

Version 1.2.1 was announced in GAP Support on 2011-04-06. It was not picked up for the redistribution, but its archive is still available at http://schmidt.nuigalway.ie/tomlib/tomlib1r2p1.tar.gz and it has 4 authors on it, including @ThomasBreuer and Thomas Merkwitz.

**Comment by ThomasBreuer** [comment]
@alex-konovalov To be precise, version 1.2.1 lists four persons, two authors and two maintainers.
I had been listed as a maintainer at that time, and later we had agreed to remove this record.

**Comment by olexandr-konovalov** [comment]
@ThomasBreuer thanks for pointing that out! Actually, the archive of 1.2.1 that I have downloaded today has 2 authors (TM, GP), 1 maintainer (LN), and 1 contributor, i.e. neither author nor maintainer (you). I hope @gpfeiffer and @LiamNaughton will look at this soon.

**Comment by fingolfin** [comment]
For the record, in version 1.1.4, shipped with GAP 4.4.12, I see this:
```
Persons := [
  rec(
    LastName := "Breuer",
    FirstNames := "Thomas",
    IsAuthor := false,
    IsMaintainer := true,
    Email := "sam@math.rwth-aachen.de",
    WWWHome := ~.MyWWWHome,
    Place := "Aachen",
    Institution := "Lehrstuhl D f&uuml;r Mathematik, RWTH Aachen",
    PostalAddress := Concatenation( [
      "Thomas Breuer\n",
      "Lehrstuhl D f&uuml;r Mathematik\n",
      "Templergraben 64\n",
      "52062 Aachen\n",
      "Germany"
      ] )
  ),
  rec(
    LastName := "Merkwitz",
    FirstNames := "Thomas",
    IsAuthor := true,
    IsMaintainer := false,
    Email := "Thomas.Merkwitz@Team4.DE"
#   WWWHome :=
  ),
  rec(
    LastName := "Pfeiffer",
    FirstNames := "G&ouml;tz",
    IsAuthor := true,
    IsMaintainer := false,
    Email := "goetz.pfeiffer@nuigalway.ie",
#   WWWHome :=
    Place := "Galway"
#   Institution := "",
#   PostalAddress := Concatenation( [
#     ] )
  ),
  ],
```

It is indeed strange that people were dropped -- I'd suggest to add both Thomases back, with `IsMaintainer:=false` for both, and `IsAuthor:=true` for Thomas Merkwitz.

**Comment by ThomasBreuer** [comment]
I think it does not make sense to list people who are neither authors nor maintainers,
thus the record for me should not be added again.
The record for Thomas Merkwitz should be added, as @fingolfin proposed;
the old e-mail address is invalid already for quite some time, and I do not know a valid one.

**Comment by fingolfin** [comment]
I do think it makes sense to list people who are neither author nor maintainer (and many packages do so), in order to represent contributors. GAP now even lists such people records as "contributors" when loading a package.

Anyway, of course it is your prerogative to decide that you do not want to be listed here as such, and that should be respected.

**Comment by fingolfin** [comment]
I submitted PR #21 which resolves this.
