### ISSUE TITLE
Set up redirect for the old website

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/tomlib#19]
http://schmidt.nuigalway.ie/tomlib/ offers version 1.2.6, while you have now https://gap-packages.github.io/tomlib/ which offers 1.2.7. I suggest to set up a redirect from the old website to the new one.

**Comment by fingolfin** [comment]
That would indeed be great; presumable @gpfeiffer will have to do it?

**Comment by olexandr-konovalov** [comment]
Indeed. Just sent an email reminder to @gpfeiffer

**Comment by olexandr-konovalov** [comment]
I see now that the link to download is updated but not the other links (README and documentation) - please fix the rest.

**Comment by fingolfin** [comment]
http://schmidt.nuigalway.ie/tomlib/ seems dead, which I guess also counts...
