### ISSUE TITLE
PackageInfo ArchiveURL does not work

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/tomlib#24]
Nothing too major!

tomlib's PackageInfo.g configures the package's archive URL like most other packages, producing the address `https://github.com/gap-packages/tomlib/releases/download/v1.2.8/tomlib-1.2.8.tar.gz` from which the package can be downloaded.  However, it seems that this URL doesn't actually work.  In particular, this prevents tomlib being installed by PackageManager.

This may be a problem with the latest github release of this package.  Looking at [the releases page](https://github.com/gap-packages/tomlib/releases), tomlib 1.2.7 has 3 assets including the actual release in bold.  tomlib 1.2.8, however, only has 2 assets, and the top one is missing.

I'm not sure what causes this, but perhaps adding an archive to the release would fix this. :)

**Comment by olexandr-konovalov** [comment]
It looks to me after inspecting the TomLib's `gh-pages` branch that you do not use https://github.com/gap-system/ReleaseTools which automates release publishing, and instead of that you do all changes manually. I suggest to go back to `ReleaseTools` - in this case, you will have one automated commit in gh-pages branch, and the releases page will have a proper `tar.gz` archive. See e.g. https://github.com/gap-packages/utils/commits/gh-pages and https://github.com/gap-packages/utils/releases.

**Comment by olexandr-konovalov** [comment]
P.S. It's actually a major problem: the new version of the package can not be picked up by the package update mechanism:
```
* TomLib - new version 1.2.8 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/tomlib/releases/download/v1.2.8/tomlib-1.2.8
[ ".tar.gz" ]
  unpacking tomlib-1.2.8.tar.gz
ERROR (TomLib): could not unpack archive .... SKIPPING !!!
```

**Comment by olexandr-konovalov** [comment]
Thank you @mtorpey for reporting this - I was quite busy recently, and did not check package update logs for a while.

**Comment by fingolfin** [comment]
Most likely, something failed when running the `release` script. This can be fixed, though, by simply re-running it, with the `--force` option. @gpfeiffer and @LiamNaughton should be able to do that, otherwise I can also do it; I am also happy to help debug any errors you might run into.

**Comment by gpfeiffer** [comment]
ok, I ran the release script with --force.  hopefully that fixes it.

**Comment by fingolfin** [comment]
The tar.gz is indeed there now
