### ISSUE TITLE
Some things to do

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/tomlib#3]
Here are some things I believe should be done before a new release.

* [x] replace references to gap-trouble@dcs.st-and.ac.uk by support@gap-system.org and/or a link the issue tracker of this repository
* [x] drop use of and reference to the .zoo file format
* [x] add a `makedoc.g` file for building the manual (this is needed for using ReleaseTools, see issue #2)
* [x] Remove CVS leftovers, like all lines containing ` @(#)$Id:`
* [x] Remove access to the obsolete GAP global record `Revision`

**Comment by olexandr-konovalov** [comment]
Also, after moving to gap-packages VO, set up Travis CI and Codecov: tools which will run tests for every change suggested in the package to check that they still run correctly after the change (e.g. like at https://travis-ci.org/gap-packages/example), and which calculate how many lines of the codebase are exercised by these tests (e.g. like at https://codecov.io/gh/gap-packages/example). We will be happy to help to set that up.

**Comment by olexandr-konovalov** [comment]
For travis CI and codecov, I've made PR #11.

Also, you may wish to revise README and make it more generic. In the past, my packages had READMEs with details of the version number, release dates etc. - redundant information which can be figured out from elsewhere, but which had to be updated manually each time a release is made. I've tried to get rid of those places, or at least reduce their number to a minimum.
