### ISSUE TITLE
data libraries should be compressed

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-packages/tomlib#8]
The tomlib/data directory is 228M.  GAP now supports transparent reading of gzip compressed files.  For GAP 4.11, is there any reason not to run "gzip -9 *" in the data subdirectory?  That reduces tomlib/data to 50M.  

I'm guessing, without having tested, that this might typically make GAP startup faster, as decompressing can be faster than reading from disk.  And data tables like this are unlikely to change often (if ever).

(In the broader context, parenthetically:  Several other GAP packages look like they would benefit from a similar change: notably simpcomp, but also transgrp, sglppow, smallgrp, irredsol, ctbllib, rcwa, primgrp.  Recog has a 21M file that would benefit.  Smallsemi and unitlib already have their data compressed.)

**Comment by olexandr-konovalov** [comment]
The feature is not in GAP 4.9 yet (?). We should include this in GAP 4.10 release announcement and advertise to package authors...

**Comment by fingolfin** [comment]
GAP always supported transparent reading of gzip compressed files, at least on *Unix* (and possibly on Cygwin, but I don't know that), but we did indeed change the implementation for this, so that it now definitely also works on Windows.

However, I would advice against compressing those text files inside this repository, as that would defeat the ability of git to store and review diffs in these files, and would also increase (!) the repository size. Instead, I would suggest to compress them "on the fly" during the release process. If you were to use the [ReleaseTools](https://github.com/gap-system/ReleaseTools), then this can be achieved via `.release` script in your package; I'd be happy to be of assistance with that.

But as @alex-konovalov points out, it is probably best to wait with that until GAP 4.10 is out.

**Comment by olexandr-konovalov** [comment]
The new version is being now picked up, and these are particular files causing warnings:
```
pkg/tomlib-1.2.7/data/tmo8m2m1.tom: up to 42 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tmo8m2m1.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tmo8p2.tom: up to 76 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tmo8p2.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tmo8m2.tom: up to 31 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tmo8m2.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tmo8p2m4.tom: up to 97 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tmo8p2m4.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tms13.tom: up to 109 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tms13.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tms12.tom: up to 38 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tms12.tom' to cancel the pending addition)
pkg/tomlib-1.2.7/data/tmhe2.tom: up to 55 MB of RAM may be required to manage this file
(use 'hg revert pkg/tomlib-1.2.7/data/tmhe2.tom' to cancel the pending addition)
```
Still, this doesn't stop the package from being picked up by the check for updates.

**Comment by RussWoodroofe** [comment]
Is this the same problem that @fingolfin mentioned with compressed files inside the repository?  It seems to be complaining about the larger files.
Maybe the best place to do it is where the packages are combined into a release?
Probably it's still better to wait until after 4.10 release, as we've all said :-).

**Comment by olexandr-konovalov** [comment]
@RussWoodroofe no, that's completely different - it comes from a mercurial repository which stores **released** packages. But as I said, the new release of tomlib has been picked up, and it should be ready for GAP 4.10 - no actions needed at the moment.

**Comment by ChrisJefferson** [comment]
Now 4.10 is out, it would be nice to do this (I've sanity checked, and indeed compressing tomlib's data libraries seems to work on all OSes I have access to).

**Comment by fingolfin** [comment]
I just submitted PR #20 which does this in the way I suggested.
